"""SQLAlchemy models. Importing this package registers every table on `Base`."""

from app.models.base import Base
from app.models.enums import (
    ActorType,
    AnomalySeverity,
    BillingFrequency,
    CriticVerdict,
    EvidenceStrength,
    HumanDecisionType,
    InvoiceStatus,
    MatchDecision,
    PaymentStatus,
    QuarantineReason,
    RecordType,
    RevenueClass,
    ReviewStatus,
    RunStatus,
    SourceSystem,
    TransactionDirection,
    UserRole,
)
from app.models.evidence import (
    BankTransaction,
    Citation,
    Contract,
    CreditNote,
    CustomerEntity,
    Invoice,
    Payment,
    QuarantinedRecord,
    RawRecord,
    Refund,
)
from app.models.verification import (
    Allocation,
    Anomaly,
    AuditEvent,
    CorrectionMemory,
    CriticDecision,
    EntityMatchProposal,
    ReportVersion,
    RevenueItem,
    ReviewItem,
    VerificationRun,
)
from app.models.workspace import ProviderConnection, User, Workspace, WorkspaceMember

__all__ = [
    "ActorType",
    "Allocation",
    "Anomaly",
    "AnomalySeverity",
    "AuditEvent",
    "BankTransaction",
    "Base",
    "BillingFrequency",
    "Citation",
    "Contract",
    "CorrectionMemory",
    "CreditNote",
    "CriticDecision",
    "CriticVerdict",
    "CustomerEntity",
    "EntityMatchProposal",
    "EvidenceStrength",
    "HumanDecisionType",
    "Invoice",
    "InvoiceStatus",
    "MatchDecision",
    "Payment",
    "PaymentStatus",
    "ProviderConnection",
    "QuarantineReason",
    "QuarantinedRecord",
    "RawRecord",
    "RecordType",
    "Refund",
    "ReportVersion",
    "RevenueClass",
    "RevenueItem",
    "ReviewItem",
    "ReviewStatus",
    "RunStatus",
    "SourceSystem",
    "TransactionDirection",
    "User",
    "UserRole",
    "VerificationRun",
    "Workspace",
    "WorkspaceMember",
]
